package main

import (
	"fmt"
	"os"
	"path/filepath"
)

const exportsManifest = `// Generated by make wasm.
// Browser JS ABI exported by wasm/main.go.

export type LndWasmErrorCallback = (error: string) => void;
export type LndWasmSuccessCallback = () => void;
export type LndWasmBytesCallback = (responseBytes: Uint8Array) => void;
export type LndWasmStringCallback = (result: string) => void;

export interface LndWasmServerStreamHandle {
  /**
   * Silences future JS callbacks locally.
   *
   * This does not cancel the underlying falafel/mobile stream yet because the
   * generated server-stream bindings do not expose a real cancellation handle.
   */
  stop(): string | null | undefined;
}

export interface LndWasmBidiStreamHandle {
  send(requestBytes: Uint8Array): string | null | undefined;
  stop(): string | null | undefined;
}

/**
 * Starts lnd asynchronously. A non-empty string return means argument or setup
 * validation failed before the async start path began.
 */
export declare function lndWasmStart(
  extraArgs: string,
  successCb: LndWasmSuccessCallback,
  errorCb: LndWasmErrorCallback,
): string | null | undefined;

/**
 * Returns the current mobile/lnd status code.
 */
export declare function lndWasmGetStatus(): number;

/**
 * Raw unary RPC entrypoint. Success responses are delivered as Uint8Array
 * payloads. Errors are delivered as strings.
 */
export declare function lndWasmInvokeRPC(
  method: string,
  requestBytes: Uint8Array,
  successCb: LndWasmBytesCallback,
  errorCb: LndWasmErrorCallback,
): string | null | undefined;

/**
 * Raw server-streaming RPC entrypoint. Stream responses are delivered as
 * Uint8Array payloads. Errors are delivered as strings.
 */
export declare function lndWasmOpenServerStream(
  method: string,
  requestBytes: Uint8Array,
  onResponse: LndWasmBytesCallback,
  onError: LndWasmErrorCallback,
): LndWasmServerStreamHandle | string | null | undefined;

/**
 * Raw bidi-streaming RPC entrypoint. Stream responses are delivered as
 * Uint8Array payloads. Errors are delivered as strings.
 */
export declare function lndWasmOpenBidiStream(
  method: string,
  onResponse: LndWasmBytesCallback,
  onError: LndWasmErrorCallback,
): LndWasmBidiStreamHandle | string | null | undefined;

/**
 * Runs speedloader graph sync asynchronously. Results are delivered as strings
 * because the underlying mobile helper returns plain status messages.
 */
export declare function lndWasmGossipSync(
  serviceUrl: string,
  cacheDir: string,
  dataDir: string,
  networkType: string,
  successCb: LndWasmStringCallback,
  errorCb: LndWasmErrorCallback,
): string | null | undefined;

/**
 * Cancels the current speedloader sync, if one is running.
 */
export declare function lndWasmCancelGossipSync(): void;
`

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: genwasmexports <output-dir>")
		os.Exit(1)
	}

	outputPath := filepath.Join(os.Args[1], "lnd-wasm-exports.d.ts")
	if err := os.MkdirAll(os.Args[1], 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "create output dir: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputPath, []byte(exportsManifest), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write exports manifest: %v\n", err)
		os.Exit(1)
	}
}
