package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/build"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"slices"
	"strings"
)

func main() {
	tagsFlag := flag.String("tags", "mobile", "space-separated build tags used for the wasm build")
	flag.Parse()

	root, err := os.Getwd()
	if err != nil {
		fail(err)
	}

	mobileDir := filepath.Join(root, "mobile")
	entries, err := os.ReadDir(mobileDir)
	if err != nil {
		fail(err)
	}

	ctx := build.Default
	ctx.GOOS = "js"
	ctx.GOARCH = "wasm"
	ctx.BuildTags = strings.Fields(*tagsFlag)

	var unary []string
	var serverStreams []string
	var bidiStreams []string
	for _, entry := range entries {
		name := entry.Name()
		if entry.IsDir() || !strings.HasSuffix(name, "_generated.go") {
			continue
		}
		match, err := ctx.MatchFile(mobileDir, name)
		if err != nil {
			fail(err)
		}
		if !match {
			continue
		}

		path := filepath.Join(mobileDir, name)
		methods, err := collectMethods(path)
		if err != nil {
			fail(err)
		}
		unary = append(unary, methods.unary...)
		serverStreams = append(serverStreams, methods.serverStreams...)
		bidiStreams = append(bidiStreams, methods.bidiStreams...)
	}

	slices.Sort(unary)
	unary = slices.Compact(unary)
	slices.Sort(serverStreams)
	serverStreams = slices.Compact(serverStreams)
	slices.Sort(bidiStreams)
	bidiStreams = slices.Compact(bidiStreams)

	unaryOut, err := renderUnaryRegistry(unary)
	if err != nil {
		fail(err)
	}
	if err := writeRegistry(
		filepath.Join(root, "wasm", "backend", "unary_registry_generated.go"),
		unaryOut,
	); err != nil {
		fail(err)
	}
	serverOut, err := renderServerStreamRegistry(serverStreams)
	if err != nil {
		fail(err)
	}
	if err := writeRegistry(
		filepath.Join(root, "wasm", "backend", "server_stream_registry_generated.go"),
		serverOut,
	); err != nil {
		fail(err)
	}
	bidiOut, err := renderBidiStreamRegistry(bidiStreams)
	if err != nil {
		fail(err)
	}
	if err := writeRegistry(
		filepath.Join(root, "wasm", "backend", "bidi_stream_registry_generated.go"),
		bidiOut,
	); err != nil {
		fail(err)
	}
}

type collectedMethods struct {
	unary         []string
	serverStreams []string
	bidiStreams   []string
}

func collectMethods(path string) (*collectedMethods, error) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, path, nil, 0)
	if err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}

	methods := &collectedMethods{}
	for _, decl := range file.Decls {
		fn, ok := decl.(*ast.FuncDecl)
		if !ok || fn.Recv != nil || !fn.Name.IsExported() {
			continue
		}
		switch {
		case isUnaryBinding(fn):
			methods.unary = append(methods.unary, fn.Name.Name)
		case isServerStreamBinding(fn):
			methods.serverStreams = append(methods.serverStreams, fn.Name.Name)
		case isBidiStreamBinding(fn):
			methods.bidiStreams = append(methods.bidiStreams, fn.Name.Name)
		}
	}

	return methods, nil
}

func isUnaryBinding(fn *ast.FuncDecl) bool {
	if fn.Type.Results != nil {
		return false
	}
	if fn.Type.Params == nil || len(fn.Type.Params.List) != 2 {
		return false
	}
	return isByteSlice(fn.Type.Params.List[0].Type) && isCallbackType(fn.Type.Params.List[1].Type)
}

func isServerStreamBinding(fn *ast.FuncDecl) bool {
	if fn.Type.Results != nil {
		return false
	}
	if fn.Type.Params == nil || len(fn.Type.Params.List) != 2 {
		return false
	}
	return isByteSlice(fn.Type.Params.List[0].Type) && isRecvStreamType(fn.Type.Params.List[1].Type)
}

func isBidiStreamBinding(fn *ast.FuncDecl) bool {
	if fn.Type.Params == nil || len(fn.Type.Params.List) != 1 {
		return false
	}
	if !isRecvStreamType(fn.Type.Params.List[0].Type) {
		return false
	}
	if fn.Type.Results == nil || len(fn.Type.Results.List) != 2 {
		return false
	}
	return isSendStreamType(fn.Type.Results.List[0].Type) && isErrorType(fn.Type.Results.List[1].Type)
}

func isByteSlice(expr ast.Expr) bool {
	array, ok := expr.(*ast.ArrayType)
	if !ok || array.Len != nil {
		return false
	}
	ident, ok := array.Elt.(*ast.Ident)
	return ok && ident.Name == "byte"
}

func isCallbackType(expr ast.Expr) bool {
	ident, ok := expr.(*ast.Ident)
	return ok && ident.Name == "Callback"
}

func isRecvStreamType(expr ast.Expr) bool {
	ident, ok := expr.(*ast.Ident)
	return ok && ident.Name == "RecvStream"
}

func isSendStreamType(expr ast.Expr) bool {
	ident, ok := expr.(*ast.Ident)
	return ok && ident.Name == "SendStream"
}

func isErrorType(expr ast.Expr) bool {
	ident, ok := expr.(*ast.Ident)
	return ok && ident.Name == "error"
}

func renderUnaryRegistry(methods []string) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by cmd/genwasmregistry. DO NOT EDIT.\n")
	buf.WriteString("//go:build js && wasm\n\n")
	buf.WriteString("package backend\n\n")
	buf.WriteString("import lndmobile \"github.com/lightningnetwork/lnd/mobile\"\n\n")
	buf.WriteString("var unaryMethods = map[string]func([]byte, lndmobile.Callback){\n")
	for _, method := range methods {
		fmt.Fprintf(&buf, "\t%q: lndmobile.%s,\n", method, method)
	}
	buf.WriteString("}\n")

	return format.Source(buf.Bytes())
}

func renderServerStreamRegistry(methods []string) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by cmd/genwasmregistry. DO NOT EDIT.\n")
	buf.WriteString("//go:build js && wasm\n\n")
	buf.WriteString("package backend\n\n")
	buf.WriteString("import lndmobile \"github.com/lightningnetwork/lnd/mobile\"\n\n")
	buf.WriteString("var serverStreamMethods = map[string]func([]byte, lndmobile.RecvStream){\n")
	for _, method := range methods {
		fmt.Fprintf(&buf, "\t%q: lndmobile.%s,\n", method, method)
	}
	buf.WriteString("}\n")

	return format.Source(buf.Bytes())
}

func renderBidiStreamRegistry(methods []string) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by cmd/genwasmregistry. DO NOT EDIT.\n")
	buf.WriteString("//go:build js && wasm\n\n")
	buf.WriteString("package backend\n\n")
	buf.WriteString("import lndmobile \"github.com/lightningnetwork/lnd/mobile\"\n\n")
	buf.WriteString("var bidiStreamMethods = map[string]func(lndmobile.RecvStream) (lndmobile.SendStream, error){\n")
	for _, method := range methods {
		fmt.Fprintf(&buf, "\t%q: lndmobile.%s,\n", method, method)
	}
	buf.WriteString("}\n")

	return format.Source(buf.Bytes())
}

func writeRegistry(path string, contents []byte) error {
	return os.WriteFile(path, contents, 0o644)
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
