name: Build LND Mobile RPC

on:
  push:
    branches: [cshared]
  pull_request:
    branches: [cshared]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: cshared

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential \
            gcc \
            libc6-dev \
            pkg-config \
            cmake \
            make

      - name: Install Go dependencies
        run: |
          go mod download
          go mod verify

      - name: Generate mobile RPC
        run: make mobile-rpc

      - name: Add required header and build CGO
        run: |
          # Create temporary file with header
          echo '#include <stdint.h>' > temp_header
          # Prepend header to the generated file
          cat temp_header mobile/cgo_utils_generated.go > mobile/cgo_utils_generated.go.new
          mv mobile/cgo_utils_generated.go.new mobile/cgo_utils_generated.go
          # Run CGO build
          make cgo

      - name: Archive mobile build
        run: |
          cd mobile/build
          zip -r ../../mobile-build.zip .

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: mobile-build
          path: mobile-build.zip
          retention-days: 7
