name: Build LND Mobile RPC

on:
  push:
    branches: [cshared]
  pull_request:
    branches: [cshared]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: cshared

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build mobile RPC
        run: |
          make mobile-rpc
          make cgo

      - name: Archive mobile build
        run: |
          cd mobile/build
          zip -r ../../mobile-build.zip .

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: mobile-build
          path: mobile-build.zip
          retention-days: 1
